name: luoyi_color_picker
description: HSV(HSB)/HSL/RGB/Material color picker inspired by all the good design for your amazing flutter apps.
version: 2.0.0
homepage: https://github.com/mchome/flutter_colorpicker

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
